"""add os_family table

Revision ID: 313116c16f34
Revises: f279a68e9a2d
Create Date: 2026-08-30 17:56:53.233810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '313116c16f34'
down_revision: Union[str, Sequence[str], None] = 'f279a68e9a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('os_families',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('os', sa.Column('display_version', sa.String(length=50), nullable=False))
    op.add_column('os', sa.Column('family_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'os', 'os_families', ['family_id'], ['id'])
    op.drop_column('os', 'display_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('os', sa.Column('display_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'os', type_='foreignkey')
    op.drop_column('os', 'family_id')
    op.drop_column('os', 'display_version')
    op.drop_table('os_families')
    # ### end Alembic commands ###
