"""init

Revision ID: 7d01e1548c51
Revises: 
Create Date: 2026-08-30 21:21:53.767236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d01e1548c51'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('cpu_desc', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('os_families',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('parent_interface', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('api_port', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_ram_gb', sa.Integer(), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('max_vms', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('os',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('display_version', sa.String(length=50), nullable=False),
    sa.Column('incus_name', sa.String(length=50), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['os_families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disk_gb', sa.Integer(), nullable=False),
    sa.Column('ram_gb', sa.Integer(), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ip_addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.Column('gateway', sa.String(length=15), nullable=False),
    sa.Column('netmask', sa.String(length=15), nullable=False),
    sa.Column('is_allocated', sa.Boolean(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_addresses_ip'), 'ip_addresses', ['ip'], unique=True)
    op.create_table('vps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CREATING', 'DELETED', name='vpsstatus'), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('ram_gb', sa.Integer(), nullable=False),
    sa.Column('disk_gb', sa.Integer(), nullable=False),
    sa.Column('expire_at', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('ip_id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ip_id'], ['ip_addresses.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['os.id'], ),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vps')
    op.drop_index(op.f('ix_ip_addresses_ip'), table_name='ip_addresses')
    op.drop_table('ip_addresses')
    op.drop_table('tariffs')
    op.drop_table('os')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('os_families')
    op.drop_table('locations')
    op.drop_table('categories')
    # ### end Alembic commands ###
