"""add parent_interface to node

Revision ID: d025ba88a408
Revises: fa0741f6bfe2
Create Date: 2026-08-29 20:00:12.421165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd025ba88a408'
down_revision: Union[str, Sequence[str], None] = 'fa0741f6bfe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('parent_interface', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'parent_interface')
    # ### end Alembic commands ###
