"""remove disk cpu ram from vps

Revision ID: d14f3e3efaff
Revises: 7d01e1548c51
Create Date: 2026-08-31 14:55:03.755686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14f3e3efaff'
down_revision: Union[str, Sequence[str], None] = '7d01e1548c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vps', 'disk_gb')
    op.drop_column('vps', 'ram_gb')
    op.drop_column('vps', 'cpu_cores')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vps', sa.Column('cpu_cores', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('vps', sa.Column('ram_gb', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('vps', sa.Column('disk_gb', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
