"""add tariff, location, category tables

Revision ID: f279a68e9a2d
Revises: d025ba88a408
Create Date: 2026-08-30 14:54:05.961680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f279a68e9a2d'
down_revision: Union[str, Sequence[str], None] = 'd025ba88a408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('cpu_desc', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disk_gb', sa.Integer(), nullable=False),
    sa.Column('ram_gb', sa.Integer(), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('nodes', sa.Column('location_id', sa.Integer(), nullable=False))
    op.add_column('nodes', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'nodes', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'nodes', 'locations', ['location_id'], ['id'])
    op.drop_column('nodes', 'country_code')
    op.add_column('vps', sa.Column('tariff_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vps', 'tariffs', ['tariff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vps', type_='foreignkey')
    op.drop_column('vps', 'tariff_id')
    op.add_column('nodes', sa.Column('country_code', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'nodes', type_='foreignkey')
    op.drop_constraint(None, 'nodes', type_='foreignkey')
    op.drop_column('nodes', 'category_id')
    op.drop_column('nodes', 'location_id')
    op.drop_table('tariffs')
    op.drop_table('locations')
    op.drop_table('categories')
    # ### end Alembic commands ###
